### ISSUE TITLE
When the name of TEntity contains Chinese, garbled code appears in reading

### ISSUE THREAD

**Issue by 3368aa** [DomCR/ACadSharp#108]
![image](https://user-images.githubusercontent.com/4023523/222700045-83940134-39b0-46d0-a77c-1ddab5b4461e.png)

**Comment by DomCR** [comment]
Hi @3368aa 

can you post an example of file where this error occurs so I can reproduce?

thanks

**Comment by 3368aa** [comment]
send a email to u

**Comment by DomCR** [comment]
`ACadSharp` reads the file with the right information, the problem seems to be with a configuration on windows that dos not allow to print Chinese characters in the console unless is configured that way.

Please check this reference link to see if this helps:
https://stackoverflow.com/questions/5750203/how-to-write-unicode-characters-to-the-console
https://stackoverflow.com/questions/36923984/c-sharp-windows-form-cannot-display-simplified-chinese-characters

Let me know if this works.

**Comment by 3368aa** [comment]
![image](https://user-images.githubusercontent.com/4023523/224522071-34620301-3f87-496c-95b7-2e7b65c2e7fe.png)

set Encoding UTF8

![image](https://user-images.githubusercontent.com/4023523/224522059-56fbb8bb-92db-4c34-907f-d162f3b9878c.png)

runtime value

![image](https://user-images.githubusercontent.com/4023523/224522086-5a5abcd8-5c02-400f-add4-2b613c01557a.png)

output value

**Comment by 3368aa** [comment]
![image](https://user-images.githubusercontent.com/4023523/224522328-52130926-4098-4981-b5e4-49e061da734f.png)
autocad 2020 display layers

**Comment by 3368aa** [comment]
![image](https://user-images.githubusercontent.com/4023523/224522328-52130926-4098-4981-b5e4-49e061da734f.png)
autocad 2020 display layers

**Comment by 3368aa** [comment]
![image](https://user-images.githubusercontent.com/4023523/226084123-d99fd224-38a0-41a9-a847-d2f9384723db.png)
![image](https://user-images.githubusercontent.com/4023523/226084152-fecd32f6-9368-4729-9242-c42a77456e19.png)

**Comment by DomCR** [comment]
I've found the error, the encoding is not implemented:
936                gb2312                       Chinese Simplified (GB2312)
The reader doesn't find the encoding and uses the default which does not support the Chinese characters.

I'll open a branch to implement the different encodings
