### ISSUE TITLE
Trying to read DXF files created in LibreCAD throws an exception

### ISSUE THREAD

**Issue by tchrdav** [DomCR/ACadSharp#120]
**Describe the bug**
I tried to open a DXF files created in LibreCAD and got a CadLib.Exceptions.DxfException

**To Reproduce**
Download LibreCAD from https://librecad.org
Create any DXF file, and save it on disk. Open with ACadSharp library.

**Expected behavior**
File must be opened without exceptions.

**Additional context**
[Circle.zip](https://github.com/DomCR/ACadSharp/files/11162160/Circle.zip)

**Comment by DomCR** [comment]
Hi @tchrdav,

I've checked the dxf, the file doesn't follow the official dxf documentation and seems to have some invalid fields, this is what I've found:
- For DIMSTYLE the field 340 should be a handle reference pointing to a STYLE but instead is the name of the STYLE, "standard"
    - 340    DIMTXSTY (handle of referenced STYLE)
- Similar case for DIMSTYLE 341 but in this case is empty which it may cause some errors when mapping the field
    - 341    DIMLDRBLK (handle of referenced BLOCK)
  
[DIMSTYLE documentation](https://help.autodesk.com/view/OARX/2021/ENU/?guid=GUID-F2FAD36F-0CE3-4943-9DAD-A9BCD2AE81DA)

- The block entity with handle 1C and name *Paper_Space has an invalid owner handle pointing to 1B which is not present in the file, the mapping can be solved using the name but this seems to be incorrect because the object doesn't exist at all.

After this investigation I've noticed that **Autocad** doesn't seem to be bother for this issues in the file and it can be opened without any problems so I'll open a branch to make the `DxfReader` more flexible for this irregularities.

Actions:
- Make sure that the `Failsafe` in the reader works properly and is able to finish the reading notifying the errors found.
- Improve the `DxfReader` to make sure that can handle references using names or handles.
