### ISSUE TITLE
Find TDCREATE from the header of DWG

### ISSUE THREAD

**Issue by amazingProj** [DomCR/ACadSharp#155]
Hello

While I was taking files extracting the header of the files by this code, I notice that the one in the header that should be TDCREATE is actually the TDUCREATE.

Could you help me find the TDCREATE from the header?

Thanks

**Comment by DomCR** [comment]
Hi @amazingProj 

I've been exploring different files using the `DwgReader` and the TDCREATE seems to match with the desired value. Could you provide some examples or images about this issue?

TDUCREATE is not stored in the dwg format, I'm looking for some documentation to find out where this field is created/processed, but I think is referenced to the TDCREATE using the Universal date/time instead of the Local date/time.

To find the TDCREATE you only need to read the file and go the the path `CadDocument.Header.CreateDateTime`

**Comment by amazingProj** [comment]
Sorry, I was wrong.
I have discovered that AutoCAD adds TDCREATE which is the convertion to local time of the original DWG time based on your timezone.
 AutoCAD takes TDCREATE of DWG and names it TDUCREATE.
