### ISSUE TITLE
Dictionary name not stored when writing to DWG

### ISSUE THREAD

**Issue by Nubbit** [DomCR/ACadSharp#397]
**Describe the bug**
The "Name" parameter of an extended dictionary/Xdictionary attached to an Entity(LwPolyline in my case) isn't stored when writing to a DwgFile when using DWG version AC1024, I also tried version AC1018 but also didn't seem to work.

**To Reproduce**

```
string FilePath = @"C:\Dev\Testfiles\sample.dwg";
CadDocument Document = new();
CadDocument NewDocument;
LwPolyline lwpoly = new();

lwpoly.CreateExtendedDictionary();
lwpoly.XDictionary.Name = "Test";
Document.Entities.Add(lwpoly);
Document.Header.Version = ACadVersion.AC1024;

using DwgWriter writ = new(FilePath, Document);
writ.Write();            

using (DwgReader reader = new DwgReader(FilePath))
NewDocument = reader.Read();
```

**Expected behavior**
The Xdictionary.name of the entity shouldn't be empty but 'Test'

**Additional context**
Even though the dictionary name is empty, the entries in the dictionary itself can be retrieved successfully from the generated DWG,

**Comment by DomCR** [comment]
Hi @Nubbit 

This is actually the expected behavior for the `XDictionary` in any `CadObject`, the property Name is there for all `NoneGraphicalObject` to optimize the code, if a `CadDictionary` is stored as an entry of another dictionary, the entry will be the same as the name, that's why is there, but if the `CadDicitonary` belongs to a `CadObject` the name will not be relevant or stored at all.

I'll add a documentation note to make this clear in case that someone else have the same issue.

Thanks for the report!
