### ISSUE TITLE
Autocad encountered an error when opening a saved dwg file. XDList could not be read.

### ISSUE THREAD

**Issue by Sring65** [DomCR/ACadSharp#503]
**Describe the bug**
Autocad encountered an error when opening a saved dwg file. XDList could not be read.

**To Reproduce**
DWG files with Chinese Cass extended attributes, after being opened and saved, prompt an error when opened using AutoCAD, with the extended attributes lost.

**Screenshots**
![image](https://github.com/user-attachments/assets/b0bbb616-78a5-482d-98d3-061ddefc0fde)
![image](https://github.com/user-attachments/assets/652539d9-b470-4d9c-ba73-825aa8a511c8)
![image](https://github.com/user-attachments/assets/1712a613-1ef1-4ace-9842-9e91aea21a3c)

**Additional context**
[DwgWriter.zip](https://github.com/user-attachments/files/18052869/DwgWriter.zip)

**Comment by DomCR** [comment]
Hi @Sring65,

Extended data is not available yet for dwg writer, that's why the XData is gone, I'll open a branch to link to this issue.

About the errors, I've fixed some issues in the latest version of the library regarding the dwg writing system, check the newer version, if the issue persist, tell me and we'll take a look.
